name: Lint script

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'book.json'
      - '.gitignore'
      - 'Dockerfile'
      - 'Dockerfile.*'
      - '.devcontainer/**'
      - '.vscode/**'
      - '.github/**'
      - '!.github/workflows/lint.yml'
      - 'docs/**'
    branches:
      - "main"

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --recursive --in-place .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Lint script with autopep8
